### ISSUE TITLE
ScoreDataExtractor crashes when stopping

### ISSUE THREAD

**Issue by b-winkler** [Viladoman/CompileScore#10]
Here is what I do:
- start command prompt as administrator (btw, same behaviour when using non-elevated mode)
- start ScoreDataExtractor
```
C:\Users\bw\AppData\Local\Temp\ScoreExtractor>ScoreDataExtractor.exe -msvc -start
Starting MSVC recording...
Recording session started successfully!
Execution Time: 08ms
```
- build some C++ projects in Visual Studio 2019
- stop ScoreDataExtractor
```
C:\Users\bw\AppData\Local\Temp\ScoreExtractor>ScoreDataExtractor.exe -msvc -stop -o %temp%\TF_Qt.scor
Stopping MSVC recording and Generating Score...
```
then Application crashes
```
Faulting application name: ScoreDataExtractor.exe, version: 0.0.0.0, time stamp: 0x600116b4
Faulting module name: ScoreDataExtractor.exe, version: 0.0.0.0, time stamp: 0x600116b4
Exception code: 0xc0000005
Fault offset: 0x000000000000b5a3
Faulting process id: 0xf28
Faulting application start time: 0x01d6f09e4e1e6d2f
Faulting application path: C:\Users\bw\AppData\Local\Temp\ScoreExtractor\ScoreDataExtractor.exe
Faulting module path: C:\Users\bw\AppData\Local\Temp\ScoreExtractor\ScoreDataExtractor.exe
Report Id: fa6ddbe0-99c7-4837-9f42-6b58d9b2fe3c
Faulting package full name: 
Faulting package-relative application ID: 
```

I am using

> Microsoft Visual Studio Professional 2019
> Version 16.7.2
> VisualStudio.16.Release/16.7.2+30413.136
> Microsoft .NET Framework
> Version 4.8.03752
> 

Not a lot of information, I am afraid. Please tell me if there is anything more specific I can provide.

Thanks in advance, Benjamin

**Comment by Viladoman** [comment]
Sorry about that. Sadly, there is not much information I can use to pinpoint the issue. 

In order to narrow it down, I would recommend to do the following steps: 
- `ScoreDataExtractor.exe -msvc -start`
- Build your sources
- `ScoreDataExtractor.exe -msvc -stop -o <yourfolder>\output.etl` (this will store the event capture in an event trace log format. Which can be later processed)
- `ScoreDataExtractor.exe -msvc -extract -i <yourfolder>\output.etl -o <yourfolder>\output.scor` (this will process the event trace log into the aggregated scor file) 

This way we can see what is the problematic step (gathering or processing)
I am pretty sure it is failing in the extraction/processing part (as the first one is mainly MS Build insights sdk calls for msvc), but always good to double check. 

If the extractor is the one crashing I would then recommend to just clone this repo, open the DataExtractorSolution, Go to the Project Settings - Debugging and use the command arguments from the last step. This way we will get a callstack. Also, because the data is already in the *etl* file VS does not need to run in Admin mode. 

Thanks for your help. Please let me know the outcome.

**Comment by b-winkler** [comment]
Hi Ramon,

thanks for the quick response. Yes, you were right, the extraction is the one causing problems, `.etl` file is created successfully.
I will try to analyze the extraction issue as you proposed, will get back to you with more infos. But this will probably take a few days.

Cheers,
Benjamin

PS: I could not find information about why ScoreGenerator needs to be started in elevated mode. Did not seem to make a difference in my environment?

**Comment by Viladoman** [comment]
No rush! Let me know what you find in there. 

I checked what you are mentioning about the elevated mode and you are right, maybe MS updated their Build insights to not require it anymore and I was still under the impression it was mandatory. I will run some tests and remove the elevated requirement if it is not needed anymore. 

Thanks for letting me know!

**Comment by b-winkler** [comment]
Sorry for the delay.
I just ran ScoreDataExtractor in Debug mode and reproduced the crash, only to find out that someone else has reported the same bug, just with more detailed information.
So, same here: OnCompilerPassStart() is being called with `activity.InputSourcePath` and `activity.OutputObjectPath == nullptr`

Benjamin

**Comment by Viladoman** [comment]
I think I got a workaround for the issue with the missing activity names meanwhile it is not fixed in the SDK. 

FYI, I left a more detailed information of the workaround in the other [issue thread](https://github.com/Viladoman/CompileScore/issues/11)

Whenever you have time could you validate if the profiler works on [version 1.5.6](https://github.com/Viladoman/CompileScore/releases/tag/v1.5.6) when using the /MP ( which was the root cause of the SDK not giving up the path names ).

Thanks for the investigation, I really appreciate it.

**Comment by b-winkler** [comment]
Hey Ramon,
workaround seems to have fixed it. At least it did not crash anymore, though I did not look into the results, yet. Will do that later.
Benni

**Comment by b-winkler** [comment]
Works perfectly!
Thanks alot!

Benni
