### ISSUE TITLE
Problems with multiple header files with same name

### ISSUE THREAD

**Issue by kamrann** [Viladoman/CompileScore#31]
In the image below, working down from the top, it's correct up to `registry.h`. However, my project has two files with that name (this is hard to avoid when using lots of third party libs). The chain of files shown to be includers of `registry.h` (those below it in the image) are in fact includers of the other file, not the one that includes `compilednodedefinition.h`.

![image](https://user-images.githubusercontent.com/2475657/181833258-de2b02f7-f5e5-4534-ac88-f4d21f49abca.png)

Not sure if this is a bug/oversight in CompileScore, or a limitation of the compilers? I also don't know at this point if this bug extends to the timings, or if it's just in the include graph. You would probably know right away whether or not they're backed by the same data.

Thanks for a great tool btw.

**Comment by Viladoman** [comment]
This issue should be fixed on MSVC extractor on the latest version. Sadly I have not pushed the extension to the marketplace yet because Clang sources return relative paths, this makes figuring out 2 header files are the same more complicated. Also I was having problems with Clang not giving me any header information in version 14+, possibly due to some regression on Clang itself.

If you are on MSVC I would recommend just trying out manually installing [v1.7.0](https://github.com/Viladoman/CompileScore/releases/tag/v1.7.0) and check if the issue is still present.

**Comment by kamrann** [comment]
Ah sorry, I should have checked for the latest release. That's awesome, I'm using with `build2` so already using the manual data extractor anyway. I'll give the latest a go and report back.

**Comment by kamrann** [comment]
From initial testing with 1.7.0, all looks to be sorted. Thanks!
