### ISSUE TITLE
Show absolute path for includes

### ISSUE THREAD

**Issue by redorav** [Viladoman/CompileScore#44]
I've been using CompileScore for some time now to profile compile times in my personal projects, excellent tool and amazing job developing it.

One thing I've found is that headers with the same name but different path are hard to tell apart, e.g. a header called string.h that lives in one path and another in another path will get bundled together. However, if string.h is included via the <> then they seem to appear as separate includes.

The other issue is that even if they appeared as different in the image below, it's hard to tell which one is which, so another suggestion is to (optionally?) show absolute paths in the columns to be able to properly tell which one is which.

![image](https://user-images.githubusercontent.com/700032/226212873-02359fad-a55f-43d6-ba05-ca0afefc72e7.png)

Thanks again!

**Comment by Viladoman** [comment]
I agree with you here. There might be some bad behavior when matching paths that are not obvious due to this. I definitely need to improve this!

As a workaround at the moment I would suggest to use the contextual menu with right click on the element and paste to a notepad the actual full path. 
![image](https://user-images.githubusercontent.com/8118743/228034236-60424576-2020-4c6e-b6a0-b1bc81be010d.png)

Not ideal, but at least it we can get the information.

**Comment by Viladoman** [comment]
I just submitted a change to display the full path to includes and units. 

If you want to try it before I bundle a new release, you can grab it from the [action artifact directly](https://github.com/Viladoman/CompileScore/actions/runs/4581765886).

**Comment by redorav** [comment]
@Viladoman Thank you so much for addressing this quickly. I've tried it and it works great, the only improvement I would make is to make the column sortable like the others, that would make it perfect :)

**Comment by Viladoman** [comment]
The full path and sorting should be up and running on [Version 1.8.4](https://github.com/Viladoman/CompileScore/releases/tag/v1.8.4).

**Comment by redorav** [comment]
Amazing, moltes gràcies
