### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by jjaine** [Viladoman/CompileScore#56]
Any plans for building an ARM version of the extension?

**Comment by Viladoman** [comment]
Hi! 
What do you mean exactly? 
As far as I know, the extension does not care on the architecture the compiler is targeting. [As long as the compiler is able to provide the data needed to compilescore to know what happened it should work.](https://github.com/Viladoman/CompileScore/wiki/Score-Generation)

Please feel free to provide more details, as I think I did not fully understand the request.

**Comment by Viladoman** [comment]
Oh I see! Sorry for the misunderstanding.

Sadly I don't have access to a Windows based ARM machine at the moment to try this out. I will have a look if I can setup a github action to validate and create a win-arm64 version. If that is not possible I might have to ask for your help to see where the roadblocks are when building the extension on your end.

**Comment by Viladoman** [comment]
I updated the vsix and the manifest in order to work on ARM64 windows machines. As said before I can't try it out on the real thing, but I managed to virtualize a win11 ARM over an apple silicon laptop, and it seems to work. 
 
I would really appreciate if you could give it a shot installing the VS2022 extension artifact generated by the github runners in this [Arm64 manifest update change](https://github.com/Viladoman/CompileScore/actions/runs/11864849049) and let me know if you see any issues.

**Comment by jjaine** [comment]
Thanks for the update! At least with my setup the updated version works 👍

**Comment by Viladoman** [comment]
Thanks for validating!! I will wrap up a new version and upload it to the market place when I have some spare time.
